apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: annotate-metadata
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: annotate-metadata
spec:
  source:
    git:
      url: https://github.com/evankanderson/carto-conventions.git
      ref:
        branch: main
    subPath: annotate-metadata
